### PR TITLE
Remove RecursionError import for python 3

### PR DESCRIPTION
**Pull request by ignas-gustainis**
@anochens @jasonm 

[Asana: "Make django-gdpr-assist fork py3 compatible"](https://app.asana.com/0/1191439406560447/1192538554885156)
As detailed in the comments, RecursionError is already present in global namespace and the exceptions module was removed. This small fix allows the module to run on python 3. Considering forum is using a tagged version of this module a few commits behind, there is a need for a discussion on how we can implement this change best:

If we can bump forum's version to the latest (including this bugfix) this will be simple, however if we'd like to keep forum on the same version as is now, we will likely need to force push.

No functional changes for python 2, therefore minimum risk.

### CODE REVIEW

**Comment by jasonm** [comment]
Given picasso is on https://github.com/minervaproject/django-gdpr-assist/tree/20.09.01 and that tag 20.09.01 is up-to-date against `development`, it seems OK to merge this PR, make a new tag (e.g. `20.09.22`), and update picasso's requirements to point to that. Does that sound right to you guys? (Mostly making sure I'm not missing anything.) @ignas-gustainis @anochens

**Comment by ignas-gustainis** [comment]
Didn't realise gdpr-assist was already bumped up to the latest version a few days ago, that simplifies things a lot. Indeed, we should be able to merge this and tag it with a minor version increment.

**Comment by anochens** [comment]
fine by me

**Comment by ignas-gustainis** [comment]
@jasonm @anochens Could one of you merge it and tag it? I don't believe I have write permissions on this repo

**Comment by anochens** [comment]
done

**Pull request merged**
